CREATE TABLE IF NOT EXISTS product (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  slug VARCHAR(220) UNIQUE,
  brand_id INTEGER REFERENCES brand(id),
  description TEXT,
  key_ingredients TEXT,
  dosage TEXT,
  dietary TEXT,
  prescription_required BOOLEAN DEFAULT FALSE,
  strength VARCHAR(50),
  category VARCHAR(50),
  medicine_type VARCHAR(50),
  images TEXT[],
  reference_books TEXT[],
  key TEXT,
  actual_price NUMERIC,
  selling_price NUMERIC,
  discount_percent NUMERIC,
  total_quantity INTEGER,
  seasonal_medicine BOOLEAN DEFAULT FALSE,
  frequently_bought BOOLEAN DEFAULT FALSE,
  top_products BOOLEAN DEFAULT FALSE,
  people_preferred BOOLEAN DEFAULT FALSE,
  maximum_discount BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
); 