create table public.product (
  id serial not null,
  name character varying(200) not null,
  brand_id integer null,
  description text null,
  key_ingredients text null,
  prescription_required boolean null default false,
  strength character varying(50) null,
  category character varying(50) null,
  medicine_type character varying(50) null,
  images text[] null,
  reference_books text[] null,
  key text null,
  actual_price numeric null,
  selling_price numeric null,
  discount_percent numeric null,
  total_quantity integer null,
  dosage text null,
  dietary text null,
  seasonal_medicine boolean null default false,
  frequently_bought boolean null default false,
  top_products boolean null default false,
  people_preferred boolean null default false,
  maximum_discount boolean null default false,
  constraint product_pkey primary key (id)
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
) 