CREATE TABLE IF NOT EXISTS product (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category_id INTEGER REFERENCES category(id) ON DELETE SET NULL,
    brand_id INTEGER REFERENCES brand(id) ON DELETE SET NULL,
    description TEXT,
    key_ingredients TEXT,
    key_benefits TEXT,
    how_to_use TEXT,
    safety_precaution TEXT,
    other_info TEXT,
    gst INTEGER,
    prescription_required BOOLEAN DEFAULT FALSE,
    strength VARCHAR(50),
    category VARCHAR(50),
    medicine_type VARCHAR(50),
    images TEXT[],
    reference_books TEXT[],
    key TEXT,
    actual_price NUMERIC,
    selling_price NUMERIC,
    discount_percent NUMERIC,
    total_quantity INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
); 